// Reads data/agarwood-plan.csv and emits lib/agarwood-plan.ts as a typed Content[]
import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const csvPath = join(root, "data", "agarwood-plan.csv");
const outPath = join(root, "lib", "agarwood-plan.ts");

function parseCSV(text) {
  const rows = [];
  let row = [];
  let cell = "";
  let inQuotes = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"' && text[i + 1] === '"') { cell += '"'; i++; }
      else if (c === '"') { inQuotes = false; }
      else { cell += c; }
    } else {
      if (c === '"') inQuotes = true;
      else if (c === ",") { row.push(cell); cell = ""; }
      else if (c === "\n") { row.push(cell); rows.push(row); row = []; cell = ""; }
      else if (c === "\r") {}
      else cell += c;
    }
  }
  if (cell.length || row.length) { row.push(cell); rows.push(row); }
  return rows;
}

const SLOT_TO_DAY = { Mon: 0, Wed: 2, Fri: 4, Sun: 6 };

// Anchor Week 1 Monday to next Monday from today.
function nextMonday(d = new Date()) {
  const x = new Date(d);
  x.setHours(0, 0, 0, 0);
  const day = x.getDay(); // 0 Sun .. 6 Sat
  const delta = (8 - day) % 7 || 7;
  x.setDate(x.getDate() + delta);
  return x;
}

const W1Mon = nextMonday();

function trackLetter(track) {
  const m = track.match(/^([A-D])/);
  return m ? m[1] : null;
}

function trackLabel(track) {
  return track.replace(/^[A-D]\s*-\s*/, "").trim();
}

const raw = readFileSync(csvPath, "utf8");
const rows = parseCSV(raw);
const headers = rows.shift();

const idx = Object.fromEntries(headers.map((h, i) => [h, i]));

const out = [];
for (let i = 0; i < rows.length; i++) {
  const r = rows[i];
  if (!r[idx["SEO Title"]]) continue;

  const weekN = parseInt(r[idx["Week"]], 10);
  const slot = r[idx["Publish Slot"]];
  const track = trackLetter(r[idx["Track"]]);
  const trackName = trackLabel(r[idx["Track"]]);
  const category = r[idx["Content Category"]];
  const topic = r[idx["Video Topic"]];
  const angle = r[idx["Storytelling Angle"]];
  const hook = r[idx["Hook Line"]];
  const visual = r[idx["Google Flow Visual Style"]];
  const title = r[idx["SEO Title"]];

  const scheduled = new Date(W1Mon);
  scheduled.setDate(scheduled.getDate() + (weekN - 1) * 7 + (SLOT_TO_DAY[slot] ?? 0));

  const brief =
`Topic: ${topic}
Angle: ${angle}
Visual style: ${visual}
Track: ${trackName}
Category: ${category}
Slot: Week ${weekN} · ${slot}`;

  const tags = [
    `track:${track?.toLowerCase()}`,
    `w${String(weekN).padStart(2, "0")}`,
    category.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
  ].filter(Boolean);

  out.push({
    id: `c_w${String(weekN).padStart(2, "0")}_${slot.toLowerCase()}`,
    rowIndex: i,
    status: "IDEA",
    title,
    hook,
    script: "",
    description: "",
    brief,
    track,
    trackName,
    category,
    visualStyle: visual,
    weekIndex: weekN,
    publishSlot: slot,
    tags,
    scheduledAt: scheduled.toISOString(),
    aiCost: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  });
}

const ts =
`// AUTO-GENERATED by scripts/build-plan.mjs — do not edit by hand.
// Re-run with: node scripts/build-plan.mjs
//
// Real 260-row production plan parsed from data/agarwood-plan.csv.
// Titles, hooks, and visual notes are the operator's own content plan;
// scheduledAt is computed at build time as "next Monday from build day".
import type { Content } from "./types";

export const AGARWOOD_PLAN: Content[] = ${JSON.stringify(out, null, 2)};

export const AGARWOOD_STATS = {
  total: ${out.length},
  weeks: ${Math.max(...out.map(o => o.weekIndex))},
  byTrack: ${JSON.stringify(
    out.reduce((acc, o) => ((acc[o.track] = (acc[o.track] || 0) + 1), acc), {}),
    null, 2
  )},
};

/** Returns a deep-cloned copy of the seed plan so the Zustand store can mutate freely. */
export const seedClone = (): Content[] =>
  AGARWOOD_PLAN.map((c) => ({ ...c, tags: [...c.tags] }));
`;

writeFileSync(outPath, ts, "utf8");
console.log(`Wrote ${out.length} rows to ${outPath}`);
console.log(`Weeks: 1..${Math.max(...out.map(o => o.weekIndex))}`);
